"""add_model_domain

Revision ID: 039285f64821
Revises: b6ba1e22cc13
Create Date: 2021-12-21 11:14:50.370159

"""

"""
 OpenVINO DL Workbench
 Migration: Add model domain

 Copyright (c) 2021 Intel Corporation

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Column, Integer
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = '039285f64821'
down_revision = 'b6ba1e22cc13'
branch_labels = None
depends_on = None

Base = declarative_base()

modeldomainenum = postgresql.ENUM('CV', 'NLP', name='modeldomainenum', create_type=False)


class _TopologyModel(Base):
    __tablename__ = 'topologies'

    id = Column(Integer, primary_key=True, autoincrement=True)

    domain = Column(modeldomainenum, nullable=True)


def upgrade():
    bind = op.get_bind()
    modeldomainenum.create(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topologies', sa.Column('domain', modeldomainenum, nullable=True))

    session = Session(bind=bind)
    topologies = session.query(_TopologyModel).all()
    for topology in topologies:
        topology.domain = 'CV'
        session.add(topology)
        session.flush()
    # ### end Alembic commands ###


def downgrade():
    raise NotImplementedError
