"""Export project

Revision ID: 13c928632d8d
Revises: daba69779917
Create Date: 2020-12-09 10:00:12.411588

"""

"""
 OpenVINO DL Workbench
 Migration: Export project

 Copyright (c) 2021 Intel Corporation

 LEGAL NOTICE: Your use of this software and any required dependent software (the “Software Package”) is subject to
 the terms and conditions of the software license agreements for Software Package, which may also include
 notices, disclaimers, or license terms for third party or open source software
 included in or with the Software Package, and your use indicates your acceptance of all such terms.
 Please refer to the “third-party-programs.txt” or other similarly-named text file included with the Software Package
 for additional details.
 You may obtain a copy of the License at
      https://software.intel.com/content/dam/develop/external/us/en/documents/intel-openvino-license-agreements.pdf
"""

from alembic import op
from migrations.utils.sql_enum_migrator import SQLEnumMigrator
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '13c928632d8d'
down_revision = 'a54b0a1e07e1'
branch_labels = None
depends_on = None

old_pipeline_types = (
    'accuracy',
    'remote_profiling',
    'local_profiling',
    'dev_cloud_profiling',
    'local_int8_calibration',
    'remote_int8_calibration',
    'dev_cloud_int8_calibration',
    'create_profiling_bundle',
    'download_log',
    'download_model',
    'deployment_manager',
    'setup',
    'ping',
    'inference_test_image',
    'generate_dataset',
    'upload_dataset',
    'export_project_report',
    'export_inference_report',
    'local_winograd_tuning'
)

new_pipeline_types = (
    *old_pipeline_types,
    'export_project'
)

old_pipeline_stages = (
    'accuracy',
    'preparing_setup_assets',
    'uploading_setup_assets',
    'configuring_environment',
    'collecting_available_devices',
    'collecting_system_information',
    'preparing_profiling_assets',
    'preparing_int8_calibration_assets',
    'profiling',
    'getting_remote_job_result',
    'download_log',
    'int8_calibration',
    'remote_int8_calibration',
    'model_analyzer',
    'generate_dataset',
    'wait_dataset_upload',
    'extract_dataset',
    'recognize_dataset',
    'validate_dataset',
    'export_project_report',
    'export_inference_report',
    'inference_test_image',
    'winograd_tuning'
)

new_pipeline_stages = (
    *old_pipeline_stages,
    'export_project'
)

old_artifacts_types = (
    'model',
    'project_report',
    'inference_report',
    'deployment_package',
    'bundle_package',
    'log',
    'job_bundle',
    'remote_job_result',
)

new_artifacts_types = (
    *old_artifacts_types,
    'project'
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_project',
                    sa.Column('job_id', sa.Integer(), nullable=False),
                    sa.Column('accuracy_job_id', sa.Integer(), nullable=True),
                    sa.Column('tab_id', sa.String(), nullable=True),
                    sa.Column('include_model', sa.Boolean(), nullable=False),
                    sa.Column('include_dataset', sa.Boolean(), nullable=False),
                    sa.Column('include_accuracy_config', sa.Boolean(), nullable=False),
                    sa.Column('include_calibration_config', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['accuracy_job_id'], ['accuracy_jobs.job_id'], ),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
                    sa.PrimaryKeyConstraint('job_id')
                    )
    # ### end Alembic commands ###
    SQLEnumMigrator(
        table_column_pairs=(('pipelines', 'type'),),
        enum_name='pipelinetypeenum',
        from_types=old_pipeline_types,
        to_types=new_pipeline_types).upgrade()
    SQLEnumMigrator(
        table_column_pairs=(('job_execution_details', 'stage'),),
        enum_name='pipelinestageenum',
        from_types=old_pipeline_stages,
        to_types=new_pipeline_stages).upgrade()
    SQLEnumMigrator(
        table_column_pairs=(('downloadable_artifacts', 'artifact_type'),),
        enum_name='artifacttypesenum',
        from_types=old_artifacts_types,
        to_types=new_artifacts_types).upgrade()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('export_project')
    # ### end Alembic commands ###
    SQLEnumMigrator(
        table_column_pairs=(('pipelines', 'type'),),
        enum_name='pipelinetypeenum',
        from_types=old_pipeline_types,
        to_types=new_pipeline_types).downgrade()
    SQLEnumMigrator(
        table_column_pairs=(('job_execution_details', 'stage'),),
        enum_name='pipelinestageenum',
        from_types=old_pipeline_stages,
        to_types=new_pipeline_stages).downgrade()
    SQLEnumMigrator(
        table_column_pairs=(('downloadable_artifacts', 'artifact_type'),),
        enum_name='artifacttypesenum',
        from_types=old_artifacts_types,
        to_types=new_artifacts_types).downgrade()
