"""add_upload_tokenizer_pipeline

Revision ID: 15a8e6df8989
Revises: 2133a18b601e
Create Date: 2021-12-01 09:21:30.488642

"""

"""
 OpenVINO DL Workbench
 Add upload tokenizer pipeline

 Copyright (c) 2021 Intel Corporation

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Enum

from migrations.utils import SQLEnumMigrator

# revision identifiers, used by Alembic.

revision = '15a8e6df8989'
down_revision = '2133a18b601e'
branch_labels = None
depends_on = None

old_pipeline_types = (
    'remote_profiling',
    'local_profiling',
    'dev_cloud_profiling',
    'local_int8_calibration',
    'remote_int8_calibration',
    'dev_cloud_int8_calibration',
    'create_profiling_bundle',
    'download_log',
    'download_model',
    'deployment_manager',
    'export_project',
    'setup',
    'ping',
    'inference_test_image',
    'generate_dataset',
    'upload_dataset',
    'upload_model',
    'download_omz_model',
    'export_project_report',
    'export_inference_report',
    'local_winograd_tuning',
    'local_accuracy',
    'remote_accuracy',
    'dev_cloud_accuracy',
    'local_per_tensor_report',
    'remote_per_tensor_report',
    'dev_cloud_per_tensor_report',
    'local_predictions_relative_accuracy_report',
    'remote_predictions_relative_accuracy_report',
    'dev_cloud_predictions_relative_accuracy_report',
)

new_pipeline_types = (
    *old_pipeline_types,
    'upload_tokenizer'
)

pipeline_type_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('pipelines', 'type'),),
    enum_name='pipelinetypeenum',
    from_types=old_pipeline_types,
    to_types=new_pipeline_types
)

old_pipeline_stages = (
    'accuracy',
    'preparing_setup_assets',
    'uploading_setup_assets',
    'configuring_environment',
    'collecting_available_devices',
    'collecting_system_information',
    'preparing_profiling_assets',
    'preparing_int8_calibration_assets',
    'preparing_accuracy_assets',
    'profiling',
    'getting_remote_job_result',
    'download_log',
    'int8_calibration',
    'remote_int8_calibration',
    'augment_dataset',
    'extract_dataset',
    'extract_text_dataset',
    'generate_dataset',
    'recognize_dataset',
    'validate_dataset',
    'validate_text_dataset',
    'wait_dataset_upload',
    'export_project_report',
    'export_inference_report',
    'wait_model_upload',
    'model_analyzer',
    'model_optimizer_scan',
    'convert_keras_model',
    'convert_model',
    'setup_environment',
    'download_omz_model',
    'convert_omz_model',
    'move_omz_model',
    'inference_test_image',
    'export_project',
    'winograd_tuning',
)

new_pipeline_stages = (
    *old_pipeline_stages,
    'wait_tokenizer_upload',
    'validate_tokenizer',
)

pipeline_stage_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('job_execution_details', 'stage'),),
    enum_name='pipelinestageenum',
    from_types=old_pipeline_stages,
    to_types=new_pipeline_stages
)

tokenizertypeenum = Enum('wordpiece', 'BPE', name='tokenizertypeenum')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenizers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tokenizer_type', tokenizertypeenum, nullable=False),
                    sa.Column('vocab_size', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['artifacts.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tokenizer_to_topology',
                    sa.Column('creation_timestamp', sa.DateTime(), nullable=False),
                    sa.Column('last_modified', sa.DateTime(), nullable=True),
                    sa.Column('tokenizer_id', sa.Integer(), nullable=False),
                    sa.Column('topology_id', sa.Integer(), nullable=False),
                    sa.Column('selected', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['tokenizer_id'], ['tokenizers.id'], ),
                    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ),
                    sa.PrimaryKeyConstraint('tokenizer_id', 'topology_id')
                    )
    op.create_table('validate_tokenizer_jobs',
                    sa.Column('job_id', sa.Integer(), nullable=False),
                    sa.Column('tokenizer_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
                    sa.ForeignKeyConstraint(['tokenizer_id'], ['tokenizers.id'], ),
                    sa.PrimaryKeyConstraint('job_id')
                    )
    op.create_table('wait_tokenizer_upload_jobs',
                    sa.Column('job_id', sa.Integer(), nullable=False),
                    sa.Column('tokenizer_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
                    sa.ForeignKeyConstraint(['tokenizer_id'], ['tokenizers.id'], ),
                    sa.PrimaryKeyConstraint('job_id')
                    )
    # ### end Alembic commands ###

    pipeline_type_enum_migrator.upgrade()
    pipeline_stage_enum_migrator.upgrade()


def downgrade():
    raise NotImplementedError
