"""create project report pipeline

Revision ID: 241ced8ef5aa
Revises: d3bd782fa555
Create Date: 2020-10-02 14:36:36.777344

"""

"""
 OpenVINO DL Workbench
 Migration: Create project report pipeline

 Copyright (c) 2020 Intel Corporation

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
"""

import sqlalchemy as sa
from alembic import op

from migrations.utils.sql_enum_migrator import SQLEnumMigrator

# revision identifiers, used by Alembic.
revision = '241ced8ef5aa'
down_revision = 'd3bd782fa555'
branch_labels = None
depends_on = None

old_pipeline_types = (
    'accuracy',
    'remote_profiling',
    'local_profiling',
    'dev_cloud_profiling',
    'local_int8_calibration',
    'remote_int8_calibration',
    'create_profiling_bundle',
    'create_int8_calibration_bundle',
    'download_log',
    'download_model',
    'deployment_manager',
    'setup',
    'ping',
    'dev_cloud_int8_calibration',
    'inference_test_image',
)

new_pipeline_types = (
    'accuracy',
    'remote_profiling',
    'local_profiling',
    'dev_cloud_profiling',
    'local_int8_calibration',
    'remote_int8_calibration',
    'create_profiling_bundle',
    'create_int8_calibration_bundle',
    'download_log',
    'export_project_report',
    'download_model',
    'deployment_manager',
    'setup',
    'ping',
    'dev_cloud_int8_calibration',
    'inference_test_image',
)

old_pipeline_stages = (
    'accuracy',
    'preparing_setup_assets',
    'uploading_setup_assets',
    'configuring_environment',
    'collecting_available_devices',
    'collecting_system_information',
    'preparing_profiling_assets',
    'preparing_int8_calibration_assets',
    'profiling',
    'getting_remote_job_result',
    'download_log',
    'int8_calibration',
    'remote_int8_calibration',
    'model_analyzer',
    'inference_test_image',
)

new_pipeline_stages = (
    'accuracy',
    'preparing_setup_assets',
    'uploading_setup_assets',
    'configuring_environment',
    'collecting_available_devices',
    'collecting_system_information',
    'preparing_profiling_assets',
    'preparing_int8_calibration_assets',
    'profiling',
    'getting_remote_job_result',
    'download_log',
    'export_project_report',
    'int8_calibration',
    'remote_int8_calibration',
    'model_analyzer',
    'inference_test_image',
)

old_artifact_types = (
    'model',
    'deployment_package',
    'bundle_package',
    'log',
    'job_bundle',
    'remote_job_result',
)

new_artifact_types = (
    'model',
    'project_report',
    'deployment_package',
    'bundle_package',
    'log',
    'job_bundle',
    'remote_job_result',
)

pipeline_type_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('pipelines', 'type'),),
    enum_name='pipelinetypeenum',
    from_types=old_pipeline_types,
    to_types=new_pipeline_types
)

pipeline_stage_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('job_execution_details', 'stage'),),
    enum_name='pipelinestageenum',
    from_types=old_pipeline_stages,
    to_types=new_pipeline_stages
)

downloadable_artifacts_type_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('downloadable_artifacts', 'artifact_type'),),
    enum_name='artifacttypesenum',
    from_types=old_artifact_types,
    to_types=new_artifact_types
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_report_export_job',
                    sa.Column('job_id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=True),
                    sa.Column('tab_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
                    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
                    sa.PrimaryKeyConstraint('job_id')
                    )
    # ### end Alembic commands ###
    pipeline_type_enum_migrator.upgrade()
    pipeline_stage_enum_migrator.upgrade()
    downloadable_artifacts_type_enum_migrator.upgrade()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_report_export_job')
    # ### end Alembic commands ###
    pipeline_type_enum_migrator.downgrade()
    pipeline_stage_enum_migrator.downgrade()
    downloadable_artifacts_type_enum_migrator.downgrade()
