"""DevCloud parent accuracy analysis

Revision ID: 4950d2e78e61
Revises: b5b57370fa87
Create Date: 2021-10-29 17:01:21.618298

"""

"""
 OpenVINO DL Workbench
 Migration: DevCloud parent accuracy analysis

 Copyright (c) 2021 Intel Corporation

 LEGAL NOTICE: Your use of this software and any required dependent software (the “Software Package”) is subject to
 the terms and conditions of the software license agreements for Software Package, which may also include
 notices, disclaimers, or license terms for third party or open source software
 included in or with the Software Package, and your use indicates your acceptance of all such terms.
 Please refer to the “third-party-programs.txt” or other similarly-named text file included with the Software Package
 for additional details.
 You may obtain a copy of the License at
      https://software.intel.com/content/dam/develop/external/us/en/documents/intel-openvino-license-agreements.pdf
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from migrations.utils import SQLEnumMigrator

revision = '4950d2e78e61'
down_revision = 'b5b57370fa87'
branch_labels = None
depends_on = None

old_pipeline_types = (
    'local_accuracy',
    'remote_accuracy',
    'dev_cloud_accuracy',
    'remote_profiling',
    'local_profiling',
    'dev_cloud_profiling',
    'local_int8_calibration',
    'remote_int8_calibration',
    'dev_cloud_int8_calibration',
    'create_profiling_bundle',
    'download_log',
    'download_model',
    'deployment_manager',
    'export_project',
    'setup',
    'ping',
    'inference_test_image',
    'generate_dataset',
    'upload_dataset',
    'upload_model',
    'download_omz_model',
    'export_project_report',
    'export_inference_report',
    'local_winograd_tuning',
    'local_per_tensor_report',
    'remote_per_tensor_report',
    'local_predictions_relative_accuracy_report',
    'remote_predictions_relative_accuracy_report',
)

new_pipeline_types = (
    *old_pipeline_types,
    'dev_cloud_predictions_relative_accuracy_report',
    'dev_cloud_per_tensor_report',
)

pipeline_type_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('pipelines', 'type'),),
    enum_name='pipelinetypeenum',
    from_types=old_pipeline_types,
    to_types=new_pipeline_types
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_dev_cloud_dataset_annotation_result_jobs',
                    sa.Column('job_id', sa.Integer(), nullable=False),
                    sa.Column('auto_annotated_dataset_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['auto_annotated_dataset_id'], ['datasets.id'], ),
                    sa.ForeignKeyConstraint(['job_id'], ['parse_dev_cloud_result_jobs.job_id'], ),
                    sa.PrimaryKeyConstraint('job_id', 'auto_annotated_dataset_id')
                    )
    op.create_table('parse_dev_cloud_per_tensor_result_jobs',
                    sa.Column('job_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['parse_dev_cloud_result_jobs.job_id'], ),
                    sa.PrimaryKeyConstraint('job_id')
                    )
    # ### end Alembic commands ###
    pipeline_type_enum_migrator.upgrade()


def downgrade():
    raise NotImplementedError(f'Downgrade is not implemented for {revision}')
