"""DevCloud parent accuracy analysis

Revision ID: 4950d2e78e61
Revises: b5b57370fa87
Create Date: 2021-10-29 17:01:21.618298

"""

"""
 OpenVINO DL Workbench
 Migration: DevCloud parent accuracy analysis

 Copyright (c) 2021 Intel Corporation

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from migrations.utils import SQLEnumMigrator

revision = '4950d2e78e61'
down_revision = 'b5b57370fa87'
branch_labels = None
depends_on = None

old_pipeline_types = (
    'local_accuracy',
    'remote_accuracy',
    'dev_cloud_accuracy',
    'remote_profiling',
    'local_profiling',
    'dev_cloud_profiling',
    'local_int8_calibration',
    'remote_int8_calibration',
    'dev_cloud_int8_calibration',
    'create_profiling_bundle',
    'download_log',
    'download_model',
    'deployment_manager',
    'export_project',
    'setup',
    'ping',
    'inference_test_image',
    'generate_dataset',
    'upload_dataset',
    'upload_model',
    'download_omz_model',
    'export_project_report',
    'export_inference_report',
    'local_winograd_tuning',
    'local_per_tensor_report',
    'remote_per_tensor_report',
    'local_predictions_relative_accuracy_report',
    'remote_predictions_relative_accuracy_report',
)

new_pipeline_types = (
    *old_pipeline_types,
    'dev_cloud_predictions_relative_accuracy_report',
    'dev_cloud_per_tensor_report',
)

pipeline_type_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('pipelines', 'type'),),
    enum_name='pipelinetypeenum',
    from_types=old_pipeline_types,
    to_types=new_pipeline_types
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_dev_cloud_dataset_annotation_result_jobs',
                    sa.Column('job_id', sa.Integer(), nullable=False),
                    sa.Column('auto_annotated_dataset_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['auto_annotated_dataset_id'], ['datasets.id'], ),
                    sa.ForeignKeyConstraint(['job_id'], ['parse_dev_cloud_result_jobs.job_id'], ),
                    sa.PrimaryKeyConstraint('job_id', 'auto_annotated_dataset_id')
                    )
    op.create_table('parse_dev_cloud_per_tensor_result_jobs',
                    sa.Column('job_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['parse_dev_cloud_result_jobs.job_id'], ),
                    sa.PrimaryKeyConstraint('job_id')
                    )
    # ### end Alembic commands ###
    pipeline_type_enum_migrator.upgrade()


def downgrade():
    raise NotImplementedError(f'Downgrade is not implemented for {revision}')
