"""Add PRC specific

Revision ID: 4c0b3ba3888d
Revises: a291f54f85ec
Create Date: 2021-07-12 13:54:58.607423

"""

"""
 OpenVINO DL Workbench
 Migration: Check if WB is runing in PRC

 Copyright (c) 2021 Intel Corporation

 LEGAL NOTICE: Your use of this software and any required dependent software (the “Software Package”) is subject to
 the terms and conditions of the software license agreements for Software Package, which may also include
 notices, disclaimers, or license terms for third party or open source software
 included in or with the Software Package, and your use indicates your acceptance of all such terms.
 Please refer to the “third-party-programs.txt” or other similarly-named text file included with the Software Package
 for additional details.
 You may obtain a copy of the License at
      https://software.intel.com/content/dam/develop/external/us/en/documents/intel-openvino-license-agreements.pdf
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Column, Boolean, Integer
from sqlalchemy.ext.declarative import declarative_base

# revision identifiers, used by Alembic.
revision = '4c0b3ba3888d'
down_revision = 'a291f54f85ec'
branch_labels = None
depends_on = None

Base = declarative_base()


class _WBInfoModel(Base):
    __tablename__ = 'wb_info'

    develop_version = 'develop'

    id = Column(Integer, primary_key=True, autoincrement=True)
    is_prc = Column(Boolean, nullable=True, default=False)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wb_info', sa.Column('is_prc', sa.Boolean(), nullable=True))
    op.add_column('omz_topologies', sa.Column('source', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wb_info', 'is_prc')
    op.drop_column('omz_topologies', 'source')

    # ### end Alembic commands ###
