"""Enable accuracy in DevCloud

Revision ID: 7f9788668528
Revises: d1d5c84cafbe
Create Date: 2021-10-07 12:58:15.491339

"""

"""
 OpenVINO DL Workbench
 Migration: Enable accuracy in DevCloud

 Copyright (c) 2021 Intel Corporation

 LEGAL NOTICE: Your use of this software and any required dependent software (the “Software Package”) is subject to
 the terms and conditions of the software license agreements for Software Package, which may also include
 notices, disclaimers, or license terms for third party or open source software
 included in or with the Software Package, and your use indicates your acceptance of all such terms.
 Please refer to the “third-party-programs.txt” or other similarly-named text file included with the Software Package
 for additional details.
 You may obtain a copy of the License at
      https://software.intel.com/content/dam/develop/external/us/en/documents/intel-openvino-license-agreements.pdf
"""
from alembic import op
import sqlalchemy as sa

from migrations.utils import SQLEnumMigrator

# revision identifiers, used by Alembic.
revision = '7f9788668528'
down_revision = 'd1d5c84cafbe'
branch_labels = None
depends_on = None


old_pipeline_types = (
    'local_accuracy',
    'remote_accuracy',
    'remote_profiling',
    'local_profiling',
    'dev_cloud_profiling',
    'local_int8_calibration',
    'remote_int8_calibration',
    'dev_cloud_int8_calibration',
    'create_profiling_bundle',
    'download_log',
    'download_model',
    'deployment_manager',
    'export_project',
    'setup',
    'ping',
    'inference_test_image',
    'generate_dataset',
    'upload_dataset',
    'upload_model',
    'download_omz_model',
    'export_project_report',
    'export_inference_report',
    'local_winograd_tuning',
    'per_tensor_report',
    'predictions_relative_accuracy_report',
)

new_pipeline_types = tuple((*old_pipeline_types, 'dev_cloud_accuracy'))

pipeline_type_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('pipelines', 'type'),),
    enum_name='pipelinetypeenum',
    from_types=old_pipeline_types,
    to_types=new_pipeline_types
)

old_dev_cloud_job_types = (
    'profiling',
    'calibration'
)

new_dev_cloud_job_types = (
    *old_dev_cloud_job_types,
    'accuracy'
)

dev_cloud_job_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('trigger_dev_cloud_jobs', 'remote_job_type'),),
    enum_name='devcloudremotejobtypeenum',
    from_types=old_dev_cloud_job_types,
    to_types=new_dev_cloud_job_types
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_dev_cloud_accuracy_result_jobs',
                    sa.Column('job_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['parse_dev_cloud_result_jobs.job_id'], ),
                    sa.PrimaryKeyConstraint('job_id'))
    # ### end Alembic commands ###
    pipeline_type_enum_migrator.upgrade()
    dev_cloud_job_enum_migrator.upgrade()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parse_dev_cloud_accuracy_result_jobs')
    # ### end Alembic commands ###
    pipeline_type_enum_migrator.downgrade()
    dev_cloud_job_enum_migrator.downgrade()
