"""add inference test image

Revision ID: c2ff2481cc2e
Revises: df69ffd99c51
Create Date: 2020-09-19 11:42:59.293421

"""

"""
 OpenVINO DL Workbench
 Migration: Add inference test image

 Copyright (c) 2020 Intel Corporation

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
"""

from alembic import op
import sqlalchemy as sa

from migrations.utils.sql_enum_migrator import SQLEnumMigrator

# revision identifiers, used by Alembic.
revision = 'c2ff2481cc2e'
down_revision = 'df69ffd99c51'
branch_labels = None
depends_on = None


old_pipeline_types = (
    'accuracy',
    'remote_profiling',
    'local_profiling',
    'dev_cloud_profiling',
    'local_int8_calibration',
    'remote_int8_calibration',
    'create_profiling_bundle',
    'create_int8_calibration_bundle',
    'download_log',
    'download_model',
    'deployment_manager',
    'setup',
    'ping',
    'dev_cloud_int8_calibration',
)

new_pipeline_types = (
    'accuracy',
    'remote_profiling',
    'local_profiling',
    'dev_cloud_profiling',
    'local_int8_calibration',
    'remote_int8_calibration',
    'create_profiling_bundle',
    'create_int8_calibration_bundle',
    'download_log',
    'download_model',
    'deployment_manager',
    'setup',
    'ping',
    'dev_cloud_int8_calibration',
    'inference_test_image',
)

old_pipeline_stages = (
    'accuracy',
    'preparing_setup_assets',
    'uploading_setup_assets',
    'configuring_environment',
    'collecting_available_devices',
    'collecting_system_information',
    'preparing_profiling_assets',
    'preparing_int8_calibration_assets',
    'profiling',
    'getting_remote_job_result',
    'download_log',
    'int8_calibration',
    'remote_int8_calibration',
    'model_analyzer',
)

new_pipeline_stages = (
    'accuracy',
    'preparing_setup_assets',
    'uploading_setup_assets',
    'configuring_environment',
    'collecting_available_devices',
    'collecting_system_information',
    'preparing_profiling_assets',
    'preparing_int8_calibration_assets',
    'profiling',
    'getting_remote_job_result',
    'download_log',
    'int8_calibration',
    'remote_int8_calibration',
    'model_analyzer',
    'inference_test_image',
)

pipeline_type_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('pipelines', 'type'),),
    enum_name='pipelinetypeenum',
    from_types=old_pipeline_types,
    to_types=new_pipeline_types
)
pipeline_stage_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('job_execution_details', 'stage'),),
    enum_name='pipelinestageenum',
    from_types=old_pipeline_stages,
    to_types=new_pipeline_stages
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_test_images',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('predictions', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['artifacts.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('inference_test_image_jobs',
                    sa.Column('job_id', sa.Integer(), nullable=False),
                    sa.Column('test_image_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
                    sa.ForeignKeyConstraint(['test_image_id'], ['inference_test_images.id'], ),
                    sa.PrimaryKeyConstraint('job_id')
                    )
    # ### end Alembic commands ###

    pipeline_type_enum_migrator.upgrade()
    pipeline_stage_enum_migrator.upgrade()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inference_test_image_jobs')
    op.drop_table('inference_test_images')
    # ### end Alembic commands ###

    pipeline_type_enum_migrator.downgrade()
    pipeline_stage_enum_migrator.downgrade()
