"""Remote Accuracy

Revision ID: d1d5c84cafbe
Revises: fe9826e2f192
Create Date: 2021-07-29 10:08:22.030980

"""

"""
 OpenVINO DL Workbench
 Migration: Remote Accuracy

 Copyright (c) 2021 Intel Corporation

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
"""

import sqlalchemy as sa
from sqlalchemy import orm
from alembic import op

# revision identifiers, used by Alembic.
from migrations.utils import SQLEnumMigrator

revision = 'd1d5c84cafbe'
down_revision = 'fe9826e2f192'
branch_labels = None
depends_on = None


old_pipeline_stages = (
    'accuracy',
    'preparing_setup_assets',
    'uploading_setup_assets',
    'configuring_environment',
    'collecting_available_devices',
    'collecting_system_information',
    'preparing_profiling_assets',
    'preparing_int8_calibration_assets',
    'profiling',
    'getting_remote_job_result',
    'download_log',
    'int8_calibration',
    'remote_int8_calibration',
    'model_analyzer',
    'generate_dataset',
    'wait_dataset_upload',
    'extract_dataset',
    'recognize_dataset',
    'validate_dataset',
    'export_project_report',
    'export_inference_report',
    'inference_test_image',
    'winograd_tuning',
    'export_project',
    'model_optimizer_scan',
    'convert_model',
    'convert_keras_model',
    'wait_model_upload',
    'download_omz_model',
    'convert_omz_model',
    'move_omz_model',
    'augment_dataset',
    'setup_environment',
    'annotate_dataset'
)

new_pipeline_stages = (
    *old_pipeline_stages,
    'preparing_accuracy_assets'
)

pipeline_stage_migrator = SQLEnumMigrator(
    table_column_pairs=(('job_execution_details', 'stage'),),
    enum_name='pipelinestageenum',
    from_types=old_pipeline_stages,
    to_types=new_pipeline_stages
)


old_pipeline_types = (
    'accuracy',
    'remote_profiling',
    'local_profiling',
    'dev_cloud_profiling',
    'local_int8_calibration',
    'remote_int8_calibration',
    'dev_cloud_int8_calibration',
    'create_profiling_bundle',
    'download_log',
    'download_model',
    'deployment_manager',
    'export_project',
    'setup',
    'ping',
    'inference_test_image',
    'generate_dataset',
    'upload_dataset',
    'upload_model',
    'download_omz_model',
    'export_project_report',
    'export_inference_report',
    'local_winograd_tuning',
    'per_tensor_report',
    'predictions_relative_accuracy_report',
)

temp_pipeline_types = (*old_pipeline_types, 'local_accuracy', 'remote_accuracy')


temp_pipeline_type_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('pipelines', 'type'),),
    enum_name='pipelinetypeenum',
    from_types=old_pipeline_types,
    to_types=tuple(temp_pipeline_types)
)

new_pipeline_types = list(set(temp_pipeline_types) - {'accuracy'})

pipeline_type_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('pipelines', 'type'),),
    enum_name='pipelinetypeenum',
    from_types=temp_pipeline_types,
    to_types=tuple(new_pipeline_types)
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('create_accuracy_scripts_jobs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('create_accuracy_bundle_jobs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['downloadable_artifacts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###
    temp_pipeline_type_enum_migrator.upgrade()

    op.execute("UPDATE pipelines SET type='local_accuracy' WHERE type='accuracy'")

    pipeline_type_enum_migrator.upgrade()
    pipeline_stage_migrator.upgrade()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('create_accuracy_scripts_jobs')
    op.drop_table('create_accuracy_bundle_jobs')
    # ### end Alembic commands ###
    temp_pipeline_type_enum_migrator.downgrade()

    op.execute("UPDATE pipelines SET type='accuracy' WHERE type='local_accuracy'")

    pipeline_stage_migrator.downgrade()
    pipeline_type_enum_migrator.upgrade()
