"""Remote Accuracy

Revision ID: d1d5c84cafbe
Revises: fe9826e2f192
Create Date: 2021-07-29 10:08:22.030980

"""

"""
 OpenVINO DL Workbench
 Migration: Remote Accuracy

 Copyright (c) 2021 Intel Corporation

 LEGAL NOTICE: Your use of this software and any required dependent software (the “Software Package”) is subject to
 the terms and conditions of the software license agreements for Software Package, which may also include
 notices, disclaimers, or license terms for third party or open source software
 included in or with the Software Package, and your use indicates your acceptance of all such terms.
 Please refer to the “third-party-programs.txt” or other similarly-named text file included with the Software Package
 for additional details.
 You may obtain a copy of the License at
      https://software.intel.com/content/dam/develop/external/us/en/documents/intel-openvino-license-agreements.pdf
"""

import sqlalchemy as sa
from sqlalchemy import orm
from alembic import op

# revision identifiers, used by Alembic.
from migrations.utils import SQLEnumMigrator

revision = 'd1d5c84cafbe'
down_revision = 'fe9826e2f192'
branch_labels = None
depends_on = None


old_pipeline_stages = (
    'accuracy',
    'preparing_setup_assets',
    'uploading_setup_assets',
    'configuring_environment',
    'collecting_available_devices',
    'collecting_system_information',
    'preparing_profiling_assets',
    'preparing_int8_calibration_assets',
    'profiling',
    'getting_remote_job_result',
    'download_log',
    'int8_calibration',
    'remote_int8_calibration',
    'model_analyzer',
    'generate_dataset',
    'wait_dataset_upload',
    'extract_dataset',
    'recognize_dataset',
    'validate_dataset',
    'export_project_report',
    'export_inference_report',
    'inference_test_image',
    'winograd_tuning',
    'export_project',
    'model_optimizer_scan',
    'convert_model',
    'convert_keras_model',
    'wait_model_upload',
    'download_omz_model',
    'convert_omz_model',
    'move_omz_model',
    'augment_dataset',
    'setup_environment',
    'annotate_dataset'
)

new_pipeline_stages = (
    *old_pipeline_stages,
    'preparing_accuracy_assets'
)

pipeline_stage_migrator = SQLEnumMigrator(
    table_column_pairs=(('job_execution_details', 'stage'),),
    enum_name='pipelinestageenum',
    from_types=old_pipeline_stages,
    to_types=new_pipeline_stages
)


old_pipeline_types = (
    'accuracy',
    'remote_profiling',
    'local_profiling',
    'dev_cloud_profiling',
    'local_int8_calibration',
    'remote_int8_calibration',
    'dev_cloud_int8_calibration',
    'create_profiling_bundle',
    'download_log',
    'download_model',
    'deployment_manager',
    'export_project',
    'setup',
    'ping',
    'inference_test_image',
    'generate_dataset',
    'upload_dataset',
    'upload_model',
    'download_omz_model',
    'export_project_report',
    'export_inference_report',
    'local_winograd_tuning',
    'per_tensor_report',
    'predictions_relative_accuracy_report',
)

temp_pipeline_types = (*old_pipeline_types, 'local_accuracy', 'remote_accuracy')


temp_pipeline_type_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('pipelines', 'type'),),
    enum_name='pipelinetypeenum',
    from_types=old_pipeline_types,
    to_types=tuple(temp_pipeline_types)
)

new_pipeline_types = list(set(temp_pipeline_types) - {'accuracy'})

pipeline_type_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('pipelines', 'type'),),
    enum_name='pipelinetypeenum',
    from_types=temp_pipeline_types,
    to_types=tuple(new_pipeline_types)
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('create_accuracy_scripts_jobs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('create_accuracy_bundle_jobs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['downloadable_artifacts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###
    temp_pipeline_type_enum_migrator.upgrade()

    op.execute("UPDATE pipelines SET type='local_accuracy' WHERE type='accuracy'")

    pipeline_type_enum_migrator.upgrade()
    pipeline_stage_migrator.upgrade()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('create_accuracy_scripts_jobs')
    op.drop_table('create_accuracy_bundle_jobs')
    # ### end Alembic commands ###
    temp_pipeline_type_enum_migrator.downgrade()

    op.execute("UPDATE pipelines SET type='accuracy' WHERE type='local_accuracy'")

    pipeline_stage_migrator.downgrade()
    pipeline_type_enum_migrator.upgrade()
