"""improt_huggingface_model

Revision ID: f7fcb58b99cd
Revises: 5be51e1d42ff
Create Date: 2022-03-09 17:44:51.759944

"""

"""
 OpenVINO DL Workbench
 Migration: improt_huggingface_model

 Copyright (c) 2022 Intel Corporation

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
"""
import sqlalchemy as sa
from alembic import op

from migrations.utils import SQLEnumMigrator

# revision identifiers, used by Alembic.
revision = 'f7fcb58b99cd'
down_revision = '5be51e1d42ff'
branch_labels = None
depends_on = None

old_model_sources = (
    'omz',
    'original',
    'ir',
)

new_model_sources = (
    *old_model_sources,
    'huggingface',
)

model_sources_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('topologies', 'source'),),
    enum_name='modelsourceenum',
    from_types=old_model_sources,
    to_types=new_model_sources
)

old_pipeline_stages = (
    'accuracy',
    'preparing_setup_assets',
    'uploading_setup_assets',
    'configuring_environment',
    'collecting_available_devices',
    'collecting_system_information',
    'preparing_profiling_assets',
    'preparing_int8_calibration_assets',
    'preparing_accuracy_assets',
    'profiling',
    'getting_remote_job_result',
    'download_log',
    'int8_calibration',
    'remote_int8_calibration',
    'augment_dataset',
    'convert_dataset',
    'extract_dataset',
    'extract_text_dataset',
    'recognize_dataset',
    'validate_dataset',
    'validate_text_dataset',
    'wait_dataset_upload',
    'export_project_report',
    'export_inference_report',
    'wait_tokenizer_upload',
    'validate_tokenizer',
    'wait_model_upload',
    'model_analyzer',
    'model_optimizer_scan',
    'convert_keras_model',
    'convert_model',
    'setup_environment',
    'download_omz_model',
    'convert_omz_model',
    'move_omz_model',
    'inference_test_image',
    'export_project',
    'preparing_reshape_model_assets',
    'reshape_model',
    'apply_model_layout',
)

new_pipeline_stages = (
    *old_pipeline_stages,
    'import_huggingface_model',
)

pipeline_stage_migrator = SQLEnumMigrator(
    table_column_pairs=(('job_execution_details', 'stage'),),
    enum_name='pipelinestageenum',
    from_types=old_pipeline_stages,
    to_types=new_pipeline_stages)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_huggingface_model_jobs',
                    sa.Column('job_id', sa.Integer(), nullable=False),
                    sa.Column('model_id', sa.Integer(), nullable=False),
                    sa.Column('huggingface_model_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
                    sa.ForeignKeyConstraint(['model_id'], ['topologies.id'], ),
                    sa.PrimaryKeyConstraint('job_id')
                    )
    # ### end Alembic commands ###

    pipeline_stage_migrator.upgrade()
    model_sources_enum_migrator.upgrade()


def downgrade():
    raise NotImplementedError(f'Downgrade is not implemented for the {revision} migration')
