"""improt_huggingface_model

Revision ID: f7fcb58b99cd
Revises: 5be51e1d42ff
Create Date: 2022-03-09 17:44:51.759944

"""

"""
 OpenVINO DL Workbench
 Migration: improt_huggingface_model

 Copyright (c) 2022 Intel Corporation

 LEGAL NOTICE: Your use of this software and any required dependent software (the “Software Package”) is subject to
 the terms and conditions of the software license agreements for Software Package, which may also include
 notices, disclaimers, or license terms for third party or open source software
 included in or with the Software Package, and your use indicates your acceptance of all such terms.
 Please refer to the “third-party-programs.txt” or other similarly-named text file included with the Software Package
 for additional details.
 You may obtain a copy of the License at
      https://software.intel.com/content/dam/develop/external/us/en/documents/intel-openvino-license-agreements.pdf
"""
import sqlalchemy as sa
from alembic import op

from migrations.utils import SQLEnumMigrator

# revision identifiers, used by Alembic.
revision = 'f7fcb58b99cd'
down_revision = '5be51e1d42ff'
branch_labels = None
depends_on = None

old_model_sources = (
    'omz',
    'original',
    'ir',
)

new_model_sources = (
    *old_model_sources,
    'huggingface',
)

model_sources_enum_migrator = SQLEnumMigrator(
    table_column_pairs=(('topologies', 'source'),),
    enum_name='modelsourceenum',
    from_types=old_model_sources,
    to_types=new_model_sources
)

old_pipeline_stages = (
    'accuracy',
    'preparing_setup_assets',
    'uploading_setup_assets',
    'configuring_environment',
    'collecting_available_devices',
    'collecting_system_information',
    'preparing_profiling_assets',
    'preparing_int8_calibration_assets',
    'preparing_accuracy_assets',
    'profiling',
    'getting_remote_job_result',
    'download_log',
    'int8_calibration',
    'remote_int8_calibration',
    'augment_dataset',
    'convert_dataset',
    'extract_dataset',
    'extract_text_dataset',
    'recognize_dataset',
    'validate_dataset',
    'validate_text_dataset',
    'wait_dataset_upload',
    'export_project_report',
    'export_inference_report',
    'wait_tokenizer_upload',
    'validate_tokenizer',
    'wait_model_upload',
    'model_analyzer',
    'model_optimizer_scan',
    'convert_keras_model',
    'convert_model',
    'setup_environment',
    'download_omz_model',
    'convert_omz_model',
    'move_omz_model',
    'inference_test_image',
    'export_project',
    'preparing_reshape_model_assets',
    'reshape_model',
    'apply_model_layout',
)

new_pipeline_stages = (
    *old_pipeline_stages,
    'import_huggingface_model',
)

pipeline_stage_migrator = SQLEnumMigrator(
    table_column_pairs=(('job_execution_details', 'stage'),),
    enum_name='pipelinestageenum',
    from_types=old_pipeline_stages,
    to_types=new_pipeline_stages)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_huggingface_model_jobs',
                    sa.Column('job_id', sa.Integer(), nullable=False),
                    sa.Column('model_id', sa.Integer(), nullable=False),
                    sa.Column('huggingface_model_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
                    sa.ForeignKeyConstraint(['model_id'], ['topologies.id'], ),
                    sa.PrimaryKeyConstraint('job_id')
                    )
    # ### end Alembic commands ###

    pipeline_stage_migrator.upgrade()
    model_sources_enum_migrator.upgrade()


def downgrade():
    raise NotImplementedError(f'Downgrade is not implemented for the {revision} migration')
